name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Inject PayPal Client ID
        run: |
          # Verify secret exists (safely)
          if [ ! -z "${{ secrets.PAYPAL_CLIENT_ID }}" ]; then
            echo "✓ PayPal Client ID is set and not empty"
            echo "window.PAYPAL_CLIENT_ID = '${{ secrets.PAYPAL_CLIENT_ID }}';" > paypal-config.js
            echo "✓ Created paypal-config.js"
          else
            echo "❌ Error: PAYPAL_CLIENT_ID secret is not set"
            exit 1
          fi

      - name: Update HTML to include config
        run: |
          sed -i '/<head>/a \    <script src="paypal-config.js"></script>' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
