name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Inject PayPal Client ID
        run: |
          echo "window.PAYPAL_CLIENT_ID = '${{ secrets.PAYPAL_CLIENT_ID }}';" > paypal-config.js

      - name: Update HTML to include config
        run: |
          sed -i '/<head>/a \    <script src="paypal-config.js"></script>' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
