name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace PayPal Client ID
        env:
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
        run: |
          if [ -z "$PAYPAL_CLIENT_ID" ]; then
            echo "Error: PAYPAL_CLIENT_ID secret is not set"
            exit 1
          fi
          # Safely replace the placeholder with the actual Client ID
          sed -i "s/%%PAYPAL_CLIENT_ID%%/$PAYPAL_CLIENT_ID/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
